function registerArticleMenu() {
  b := document.querySelector("div.subtitle");
  c := document.getElementById("jump-to-article");
  b.addEventListener("click", (e) => {
    if(b.getAttribute("show-jump")==null){
      b.setAttribute("show-jump","");
      e.stopPropagation();
    }
  });

  window.addEventListener("click", (e) => {
    if(e.target!=c) {
      b.removeAttribute("show-jump")
    }
  });
}

registerArticleMenu();
