import "std/stats";


function registerHamburgerMenu() {
  let c=document.getElementById('nav-links');
  let b=document.getElementById('hamburger-menu-button');

  b.addEventListener('click', ()=>{
    if(b.getAttribute('selected') == null){
      c.setAttribute('show','');
      b.setAttribute('selected','');
    }else{
      c.removeAttribute('show');
      b.removeAttribute('selected');
    }
  });
}

registerHamburgerMenu();
